services.akkoma.config.":pleroma".":mrf_simple".reject = [
  (lib.nameValuePair "13bells.com" "admin posts sandy hook conspiracy theories, vaccine misinformation, transmisia, queermisia")
  (lib.nameValuePair "1611.social" "antisemitism and anti-vax from admin; antisemitic caricatures")
  (lib.nameValuePair "4aem.com" "freeze peach peertube hosting antisemitic content and \"clown world\" dogwhistles")
  (lib.nameValuePair "5dollah.click" "extreme racism and racial slurs from staff accounts; no listed rules")
  (lib.nameValuePair "adachi.party" "about page features racial slurs and \"kill/behead\" copypasta; rules later updated to require advocacy for racism/fascism/nazism; admin posts racist transmisia")
  (lib.nameValuePair "adtension.com" "admin posts anti-black racism and doubled down when called out")
  (lib.nameValuePair "annihilation.social" "run by same person as dembased.xyz; see dembased.xyz")
  (lib.nameValuePair "dembased.xyz" "block-notification bot; racism and antisemitism from admin and local users")
  (lib.nameValuePair "anon-kenkai.net" "antisemitic caricature on peertube landing page; admin posts anti-pride content")
  (lib.nameValuePair "asbestos.cafe" "racism, ableism, antisemitism from admin; shared a dox attempt; extreme anti-blackness from local users")
  (lib.nameValuePair "bae.st" "run by same person as skippers-bin.com; see skippers-bin.com")
  (lib.nameValuePair "skippers-bin.com" "admin has \"n-word pass\" on profile; runs lolicon and black-fetishism bots; runs major followbot; rejects deletes; confederate flag on another admin's profile")
  (lib.nameValuePair "banepo.st" "block-notification bot; admin posts antisemitism, homomisia, transmisia, and ableism")
  (lib.nameValuePair "bassam.social" "admin frames opposition to anti-queer discrimination as \"oppression\"; doubled down on permitting bigotry after reports")
  (lib.nameValuePair "beefyboys.win" "block-notification bot; staff posts \"racism is cool and natural\" with racial slurs")
  (lib.nameValuePair "boymoder.biz" "anti-indian racism and racist copypasta from admin; staff overlaps with asbestos.cafe")
  (lib.nameValuePair "brainsoap.net" "admin dismissive of white supremacy; nazi humor")
  (lib.nameValuePair "breastmilk.club" "admin posts transmisic sui-bait and spams mutual aid spaces with queermisia")
  (lib.nameValuePair "brighteon.social" "far-right instance connected to the brighteon network")
  (lib.nameValuePair "cachapa.xyz" "admin posts blatant racism and transmisic sui-bait; about page contains slurs; permits lolicon")
  (lib.nameValuePair "cachapa.cc" "same admin/issues as cachapa.xyz")
  (lib.nameValuePair "caekis.love" "extreme anti-black racism and antisemitism including genocide advocacy; participated in queermisic harassment campaign")
  (lib.nameValuePair "cannibal.cafe" "pro-contact admin; staff-endorsed instances include known csam/pro-contact instances")
  (lib.nameValuePair "catgirl.life" "part of waifu hunter club; permits lolicon; used for block-evasion by admin")
  (lib.nameValuePair "peervideo.club" "part of waifu hunter club alongside catgirl.life; same issues")
  (lib.nameValuePair "cawfee.club" "racism including anti-romani posts from admin; anti-vax from admin")
  (lib.nameValuePair "childlove.space" "pro-contact map instance that explicitly allows minors to register")
  (lib.nameValuePair "childlove.su" "same as childlove.space; multiple identified pro-contact users and newgon connections")
  (lib.nameValuePair "clew.lol" "racist memes and slurs from admin; white nationalist users; transmisogynistic harassment with sui-bait")
  (lib.nameValuePair "clubcyberia.co" "anti-black emotes; blatant racism from users; hosts kiwifarms staff; staff publicizes reports against harassment victims")
  (lib.nameValuePair "cottoncandy.cafe" "pro-contact map admin; local bubble endorses other pro-contact instances")
  (lib.nameValuePair "crlf.ninja" "admin encourages sending racist slurs to people who block instances; transmisic dogpile participation; publicizes blocks; antisemitic dogwhistle")
  (lib.nameValuePair "crucible.world" "admin participates in extreme transmisic harassment")
  (lib.nameValuePair "cum.camp" "rejects deletes; block-notification bot; staff posts csa-adjacent content")
  (lib.nameValuePair "cum.salon" "same issues as cum.camp; published dox materials")
  (lib.nameValuePair "cunnyborea.space" "racist pro-contact pedophilia-themed instance; admin bios feature swastikas, \"total ___ death\", racism, and antisemitism")
  (lib.nameValuePair "decayable.ink" "well-known harassment campaigns; transmisogynistic harassment; racist admin")
  (lib.nameValuePair "detroitriotcity.com" "explicit nazi instance; about page permits racial slurs and anti-lgbt content; permits lolicon")
  (lib.nameValuePair "djsumdog.com" "admin posts blatant transmisia and defends teaching children to be transmisic; jan 6 conspiracy theories")
  (lib.nameValuePair "drinkanddrive.africa" "extreme anti-blackness and antisemitism")
  (lib.nameValuePair "eientei.org" "about page explicitly describes instance as racist and uses slurs; block-notification bot; rejects deletes; antisemitic caricatures from admin")
  (lib.nameValuePair "eveningzoo.club" "transmisia, racism, antisemitism, and white nationalism from admin and users")
  (lib.nameValuePair "feministwiki.org" "admin pedojackets and misgenders trans people; promotes transphobia as moral imperative; terf-focused root domain")
  (lib.nameValuePair "fluf.club" "transmisia and sui-bait from admin; about page recommends other fedinuke instances")
  (lib.nameValuePair "foxgirl.lol" "antisemitic slurs and transmisic slurs from admin")
  (lib.nameValuePair "freak.university" "permits pedophilia and explicitly allows minors (13+); contains untagged sexual depictions of minors and pro-contact users")
  (lib.nameValuePair "pedo.school" "identical rules and issues to freak.university; same instance network")
  (lib.nameValuePair "freeatlantis.com" "far-right maga instance; admin reblogs extreme transmisogyny, anti-vax, qanon")
  (lib.nameValuePair "freespeechextremist.com" "antisemitism, transmisogyny; block-notification bot; rejects deletes; explicit freeze-peach policy")
  (lib.nameValuePair "fsebugoutzone.org" "continuation of freespeechextremist.com; same policies and issues")
  (lib.nameValuePair "froth.zone" "blatant racism and racist homomisia; ableism from admin; no rules against hate speech")
  (lib.nameValuePair "gameliberty.club" "permits lolicon; admin posts racist memes; slurs in admin bio")
  (lib.nameValuePair "gearlandia.haus" "transmisic targeted harassment and sui-bait from multiple staff; racist slurs from staff; queermisia; staff posts lolisho")
  (lib.nameValuePair "geofront.rocks" "nazi instance; blatant racist and transmisic slurs; ethno-nationalism; nazi profile from active user")
  (lib.nameValuePair "genderheretics.xyz" "about page explicitly identifies as transmisic; admin posts nsfl medical gore in transmisogynistic context; anti-drag pedojacketing")
  (lib.nameValuePair "gleasonator.com" "admin is an outspoken terf and was head of engineering for truth social; refuses to act on extreme bigotry from local users")
  (lib.nameValuePair "glee.li" "racist harassment, transmisia, and harassment campaign participation from admin; associated with getgle.org")
  (lib.nameValuePair "goyim.social" "anti-black caricatures, antisemitism, holocaust denial, and white pride from primary user")
  (lib.nameValuePair "harpy.faith" "antisemitism and racist slurs from admin; transmisic sui-bait directed at trans women")
  (lib.nameValuePair "h5q.net" "hosts untagged ai-generated photorealistic erotic content; potential legal risk")
  (lib.nameValuePair "haeder.net" "admin blocklist reasons are explicitly queermisic; admin bio has blatant transmisia and anti-woke hashtags")
  (lib.nameValuePair "hitchhiker.social" "sibling instance of djsumdog.com; same admin and issues")
  (lib.nameValuePair "battlepenguin.video" "sibling instance of djsumdog.com; same admin and issues")
  (lib.nameValuePair "iddqd.social" "admin posts anti-black caricatures and supports predatory retaliation against dei; markets instance to 4chan users")
  (lib.nameValuePair "kitsunemimi.club" "racist and transmisic harassment from admin including ttd posts; block-notification bot")
  (lib.nameValuePair "kiwifarms.cc" "official kiwifarms fediverse instance")
  (lib.nameValuePair "kyaruc.moe" "admin posts sui-bait to get on blocklists; attempted dox; racist slurs; ableist harassment")
  (lib.nameValuePair "leafposter.club" "antisemitism, queermisia, swerf, and racist slurs from local users")
  (lib.nameValuePair "liberdon.com" "freeze-peach ancap instance; covid misinformation, anti-vax, transmisia, flat-earth, antisemitism, and blatant nazism across users")
  (lib.nameValuePair "ligma.pro" "admin threatened mass violence and animal cruelty; posted gore; bragged about death threats")
  (lib.nameValuePair "loli.church" "racist and antisemitic instance announcement; freeze-peach policy; users have uncensored lolicon hentai in profiles")
  (lib.nameValuePair "lolicon.rocks" "owner explicitly claims no content moderation; racist and ableist slurs in owner bio; antisemitism and racism from owner")
  (lib.nameValuePair "lolison.network" "map/pedophilia-focused instance")
  (lib.nameValuePair "lolison.top" "map/pedophilia-focused instance; admin also runs rapemeat.express")
  (lib.nameValuePair "magicka.org" "antisemitism, homomisic slurs, climate denial, and anti-abortion from admin")
  (lib.nameValuePair "marsey.moe" "holocaust denial memes; racism; transmisia from users and staff")
  (lib.nameValuePair "taihou.website" "staff posts rape threats, anti-vax, and racist xenomisia; continuation of marsey.moe staff")
  (lib.nameValuePair "merovingian.club" "self-described \"redpilled exiles\" instance; racist caricatures, deep misogyny, transmisogyny, antisemitism, anti-vax")
  (lib.nameValuePair "midwaytrades.com" "runs libs of tiktok bot; transmisic and misogynist admin")
  (lib.nameValuePair "mirr0r.city" "paraphilia/pedophilia-focused instance that explicitly welcomes pro-contacts and neo-nazis")
  (lib.nameValuePair "mouse.services" "blatant racist slurs from admin")
  (lib.nameValuePair "morale.ch" "transmisia, antisemitism, and ableist holocaust denial from admin")
  (lib.nameValuePair "mugicha.club" "transmisic harassment, anti-asian slurs, and misogynistic racism from admin; confederate flag users")
  (lib.nameValuePair "natehiggers.online" "domain is a racist spoonerism; blog hosts covid conspiracy theories, violent racist transmisogyny, anti-vax")
  (lib.nameValuePair "narrativerry.xyz" "anti-indian racism; antisemitic conspiracy theories mixed with homomisia and racism from admin")
  (lib.nameValuePair "nobodyhasthe.biz" "predecessor to nationalist.social; same admin and staff")
  (lib.nameValuePair "nationalist.social" "white supremacist and antisemitic admins; nazi-iconography mods; staff encourages using slurs instead of reporting")
  (lib.nameValuePair "peertube.se" "instance self-affiliates with the nordic resistance movement")
  (lib.nameValuePair "shortstacksran.ch" "ethno-fascist harassment and antisemitism from admin; blatant racist slurs from admin and users")
  (lib.nameValuePair "needs.vodka" "continuation of shortstacksran.ch; same admin and issues")
  (lib.nameValuePair "nicecrew.digital" "anti-black racism and antisemitic covid conspiracy from staff; bot that spams racial slurs")
  (lib.nameValuePair "nightshift.social" "anti-black racism and antisemitism from multiple staff members")
  (lib.nameValuePair "nnia.space" "pro-zoosexuality and pro-map instance; allows minors and pro-contact users")
  (lib.nameValuePair "nnia.cc" "claimed continuation of nnia.space; same issues")
  (lib.nameValuePair "noagendasocial.com" "far-right instance connected to the no agenda show; queermisia; ethno-nationalist users")
  (lib.nameValuePair "noagendasocial.nl" "sibling instance of noagendasocial.com")
  (lib.nameValuePair "noagendatube.com" "sibling instance of noagendasocial.com")
  (lib.nameValuePair "noauthority.social" "run by noagendasocial.com admin; transmisia; links to other freeze-peach fedinuke instances")
  (lib.nameValuePair "norwoodzero.net" "admin runs transmisic harassment campaigns and recruits users for them; about page has racial slurs and a \"whites only\" banner")
  (lib.nameValuePair "nyanide.com" "transmisogynistic pedojacketing harassment, extreme racism, and anti-vax harassment from staff")
  (lib.nameValuePair "onionfarms.org" "official kiwifarms and onionfarms community instance")
  (lib.nameValuePair "pawlicker.com" "root domain hosts pro-kiwifarms and transmisic essay; transmisogyny from admin")
  (lib.nameValuePair "pawoo.net" "lolicon-permitting instance with repeated csam incidents left unmoderated")
  (lib.nameValuePair "parcero.bond" "racist slurs, antisemitism, sui-bait, and transmisia from admin")
  (lib.nameValuePair "parcero.casa" "same admin and issues as parcero.bond")
  (lib.nameValuePair "piazza.today" "climate denial, covid misinformation, transmisia, maga, and great replacement conspiracy theories from admin and users")
  (lib.nameValuePair "pibvt.net" "lolisho and actual photos of toddlers posted by map users")
  (lib.nameValuePair "pieville.net" "admin is a white nationalist who explicitly advocates for an ethno-state and genocide; blatant racism and antisemitism")
  (lib.nameValuePair "poa.st" "well-known nazi instance")
  (lib.nameValuePair "poast.org" "affiliated with poa.st")
  (lib.nameValuePair "poast.tv" "affiliated with poa.st")
  (lib.nameValuePair "pisskey.io" "run by poa.st admin; racist, transmisic, and antisemitic harassment")
  (lib.nameValuePair "sad.cab" "also run by poa.st admin; same issues")
  (lib.nameValuePair "poster.place" "staff spams mutual aid spaces with extreme queermisia and racist homomisic posts; slur-filled instance header")
  (lib.nameValuePair "rapemeat.solutions" "openly pro-csa; successor to instance known for posting real csam")
  (lib.nameValuePair "rapemeat.express" "public counterpart to rapemeat.solutions; same admin")
  (lib.nameValuePair "rayci.st" "racial slurs, anti-indian racism, antisemitism, and shock content spam in mutualaid hashtag from admin")
  (lib.nameValuePair "rebelbase.site" "transmisia and misgendering from admin; anti-abortion; mra; covid denial; anti-vax; queermisia from users")
  (lib.nameValuePair "ryona.agency" "racism, antisemitism, transmisogynistic harassment from admin; block-notification bot; rejects deletes; bypasses authorized-fetch")
  (lib.nameValuePair "plagu.ee" "run by ryona.agency admin; same mrf policies and patches")
  (lib.nameValuePair "schwartzwelt.xyz" "admin posts transmisic sui-bait with nazi iconography; anti-indigenous racist harassment")
  (lib.nameValuePair "seal.cafe" "transmisic targeted harassment and racist slurs from admin; antisemitism from users; sui-bait toward trans women")
  (lib.nameValuePair "shaw.app" "admin pedojackets trans people and leaves transmisic replies to trans women; anti-mask")
  (lib.nameValuePair "shitpost.cloud" "racial slurs from admin; publicizes reports made against transmisic harassment targets; racist staff")
  (lib.nameValuePair "skinheads.social" "white-nationalist skinhead network (the antisocial network); white pride, nazi iconography, nordic resistance movement content")
  (lib.nameValuePair "skinheads.eu" "alternate domain for the antisocial network")
  (lib.nameValuePair "skinheads.uk" "alternate domain for the antisocial network")
  (lib.nameValuePair "skinheads.io" "alternate domain for the antisocial network")
  (lib.nameValuePair "spinster.xyz" "terf instance created by gleasonator.com admin; staff openly identifies as terf; transmisogyny")
  (lib.nameValuePair "neenster.org" "shares staff with spinster.xyz; self-described terf content")
  (lib.nameValuePair "strelizia.net" "rejects deletes; block-notification bot; anti-black racism from admin; users with nazi imagery")
  (lib.nameValuePair "subs4social.xyz" "antisemitism, misogyny, racism, transmisia, and white genocide conspiracy from the sole active user")
  (lib.nameValuePair "tastingtraffic.net" "admin repeatedly mass-posts far-right transmisia and queermisia with hashtag spam")
  (lib.nameValuePair "theblab.org" "explicitly permits and admin reblogs nazi and ethno-nationalist content; self-described gab refugee instance")
  (lib.nameValuePair "thechimp.zone" "admin sends transmisic pedojacketing harassment with racial slurs; queermisic harassment; racial slurs in admin profile")
  (lib.nameValuePair "thenobody.club" "transmisogynistic harassment, racist and antisemitic slurs, and xenomisia from admin")
  (lib.nameValuePair "truthsocial.co.in" "far-right maga-themed instance; unmoderated; racist content from primary users")
  (lib.nameValuePair "tsundere.love" "admin is an alt of a loli.church user with explicit lolicon content; extreme anti-blackness and racism")
  (lib.nameValuePair "usualsuspects.lol" "admin led targeted transmisic bodyshaming harassment campaign; created as block-bait instance")
  (lib.nameValuePair "vampiremaid.cafe" "white nationalism, racism, antisemitism with slurs from admin; suggestive lolicon")
  (lib.nameValuePair "varishangout.net" "permits lolicon/shotacon; transmisia and transmisic harassment from staff and members")
  (lib.nameValuePair "volk.network" "\"white power alt-tech\" admin with nazi salute profile photo; white supremacy and antisemitism")
  (lib.nameValuePair "volk.love" "peertube instance affiliated with volk.network; explicitly white supremacist")
  (lib.nameValuePair "vtuberfan.social" "racism and hate speech from admin; unmarked nudity; racist baiting from users")
  (lib.nameValuePair "wolfgirl.bar" "admin posts nazi content with racial slurs and defends slavery; sends nazi imagery to jewish users")
  (lib.nameValuePair "yggdrasil.social" "about page explicitly bans lgbtq; transmisia; swastika-using national socialist users; racism")
  (lib.nameValuePair "zhub.link" "admin posts queermisia and homomisia unprompted; islamomisic pedojacketing from admin")
  (lib.nameValuePair "absolutelyproprietary.org" "racial slur as admin self-intro; racist caricature threads; alts for crlf.ninja and cum.salon admins; racist slur spam in black mastodon and mutualaid")
  (lib.nameValuePair "baraag.net" "lolicon-focused instance; potential legal risk depending on jurisdiction; consider blocking media only")
  (lib.nameValuePair "berserker.town" "admin refuses to moderate hate speech; permissive policies enable eugenics dogwhistles")
  (lib.nameValuePair "federated.fun" "blatant transmisia from admin")
  (lib.nameValuePair "wikileaks2.org" "continuation of federated.fun admin's activity; queermisia on new instance")
  (lib.nameValuePair "firedragonstudios.com" "previously hosted freeze-peach instance with far-right content and anti-vax; got widely blocked before switching domains; current subdomain appears inactive")
  (lib.nameValuePair "freesoftwareextremist.com" "ableism, antisemitism from users; admin regularly uses anti-chinese and other anti-asian racial slurs; open registration")
  (lib.nameValuePair "freetalklive.com" "self-identified unmoderated instance connected to libertarian free talk live show")
  (lib.nameValuePair "kawa-kun.net" "rejects deletes")
  (lib.nameValuePair "kompost.cz" "racism, transmisia, queermisia from admin")
  (lib.nameValuePair "krackhou.se" "admin posts racist tnd content and racial slurs")
  (lib.nameValuePair "maladaptive.art" "racism, transmisia, and antisemitism from local user")
  (lib.nameValuePair "novoa.nagoya" "antisemitism from admin")
  (lib.nameValuePair "occultist.space" "run by usualsuspects.lol admin")
  (lib.nameValuePair "enjoyer.network" "run by usualsuspects.lol admin; confirmed same person")
  (lib.nameValuePair "peister.org" "admin's pinned post and profile are explicitly terf/gender-critical")
  (lib.nameValuePair "shitposter.club" "transmisia, white supremacy, racism, eugenics from multiple users; freeze-peach admin; racist admin")
  (lib.nameValuePair "shitposter.world" "successor to shitposter.club; same issues; rejects deletes")
  (lib.nameValuePair "shota.house" "freeze-peach instance permitting lolicon; staff defends bigotry; racist black fetishism from users")
  (lib.nameValuePair "burger.rodeo" "sibling instance to shota.house; same policies and staff")
  (lib.nameValuePair "soc0.outrnat.nl" "self-professed fascist admin; alleges reverse-racism; csem accusations against users; encourages hashtag spam")
  (lib.nameValuePair "someotherguy.xyz" "xenomisic \"build the wall\" admin; queermisic pedojacketing")
  (lib.nameValuePair "starnix.network" "staff includes admin of dembased.xyz and annihilation.social")
  (lib.nameValuePair "whinge.town" "racism and ableist misogyny from staff")
  (lib.nameValuePair "whinge.house" "same admin and issues as whinge.town")
  (lib.nameValuePair "wideboys.org" "affiliated with and part of same network as beefyboys.win; staff and member overlap")
];
